/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ApiApplicationsRouteImport } from './routes/api/applications'
import { Route as PricingSuccessRouteImport } from './routes/pricing/success'
import { Route as ApiAdminAuthRouteImport } from './routes/api/admin/auth'
import { Route as ApiAdminPaymentsRouteImport } from './routes/api/admin/payments'
import { Route as ApiPaymentsCheckoutRouteImport } from './routes/api/payments/checkout'
import { Route as ApiPaymentsInvoiceRouteImport } from './routes/api/payments/invoice'
import { Route as ApiPaymentsSessionRouteImport } from './routes/api/payments/session'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApplicationsRoute = ApiApplicationsRouteImport.update({
  id: '/api/applications',
  path: '/api/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingSuccessRoute = PricingSuccessRouteImport.update({
  id: '/pricing/success',
  path: '/pricing/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthRoute = ApiAdminAuthRouteImport.update({
  id: '/api/admin/auth',
  path: '/api/admin/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPaymentsRoute = ApiAdminPaymentsRouteImport.update({
  id: '/api/admin/payments',
  path: '/api/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsCheckoutRoute = ApiPaymentsCheckoutRouteImport.update({
  id: '/api/payments/checkout',
  path: '/api/payments/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsInvoiceRoute = ApiPaymentsInvoiceRouteImport.update({
  id: '/api/payments/invoice',
  path: '/api/payments/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsSessionRoute = ApiPaymentsSessionRouteImport.update({
  id: '/api/payments/session',
  path: '/api/payments/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/api/applications': typeof ApiApplicationsRoute
  '/pricing/success': typeof PricingSuccessRoute
  '/api/admin/auth': typeof ApiAdminAuthRoute
  '/api/admin/payments': typeof ApiAdminPaymentsRoute
  '/api/payments/checkout': typeof ApiPaymentsCheckoutRoute
  '/api/payments/invoice': typeof ApiPaymentsInvoiceRoute
  '/api/payments/session': typeof ApiPaymentsSessionRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/api/applications': typeof ApiApplicationsRoute
  '/pricing/success': typeof PricingSuccessRoute
  '/api/admin/auth': typeof ApiAdminAuthRoute
  '/api/admin/payments': typeof ApiAdminPaymentsRoute
  '/api/payments/checkout': typeof ApiPaymentsCheckoutRoute
  '/api/payments/invoice': typeof ApiPaymentsInvoiceRoute
  '/api/payments/session': typeof ApiPaymentsSessionRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/api/applications': typeof ApiApplicationsRoute
  '/pricing/success': typeof PricingSuccessRoute
  '/api/admin/auth': typeof ApiAdminAuthRoute
  '/api/admin/payments': typeof ApiAdminPaymentsRoute
  '/api/payments/checkout': typeof ApiPaymentsCheckoutRoute
  '/api/payments/invoice': typeof ApiPaymentsInvoiceRoute
  '/api/payments/session': typeof ApiPaymentsSessionRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/privacy'
    | '/api/applications'
    | '/pricing/success'
    | '/api/admin/auth'
    | '/api/admin/payments'
    | '/api/payments/checkout'
    | '/api/payments/invoice'
    | '/api/payments/session'
    | '/api/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/privacy'
    | '/api/applications'
    | '/pricing/success'
    | '/api/admin/auth'
    | '/api/admin/payments'
    | '/api/payments/checkout'
    | '/api/payments/invoice'
    | '/api/payments/session'
    | '/api/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/privacy'
    | '/api/applications'
    | '/pricing/success'
    | '/api/admin/auth'
    | '/api/admin/payments'
    | '/api/payments/checkout'
    | '/api/payments/invoice'
    | '/api/payments/session'
    | '/api/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  PrivacyRoute: typeof PrivacyRoute
  ApiApplicationsRoute: typeof ApiApplicationsRoute
  PricingSuccessRoute: typeof PricingSuccessRoute
  ApiAdminAuthRoute: typeof ApiAdminAuthRoute
  ApiAdminPaymentsRoute: typeof ApiAdminPaymentsRoute
  ApiPaymentsCheckoutRoute: typeof ApiPaymentsCheckoutRoute
  ApiPaymentsInvoiceRoute: typeof ApiPaymentsInvoiceRoute
  ApiPaymentsSessionRoute: typeof ApiPaymentsSessionRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/applications': {
      id: '/api/applications'
      path: '/api/applications'
      fullPath: '/api/applications'
      preLoaderRoute: typeof ApiApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/success': {
      id: '/pricing/success'
      path: '/pricing/success'
      fullPath: '/pricing/success'
      preLoaderRoute: typeof PricingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth': {
      id: '/api/admin/auth'
      path: '/api/admin/auth'
      fullPath: '/api/admin/auth'
      preLoaderRoute: typeof ApiAdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/payments': {
      id: '/api/admin/payments'
      path: '/api/admin/payments'
      fullPath: '/api/admin/payments'
      preLoaderRoute: typeof ApiAdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/checkout': {
      id: '/api/payments/checkout'
      path: '/api/payments/checkout'
      fullPath: '/api/payments/checkout'
      preLoaderRoute: typeof ApiPaymentsCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/invoice': {
      id: '/api/payments/invoice'
      path: '/api/payments/invoice'
      fullPath: '/api/payments/invoice'
      preLoaderRoute: typeof ApiPaymentsInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/session': {
      id: '/api/payments/session'
      path: '/api/payments/session'
      fullPath: '/api/payments/session'
      preLoaderRoute: typeof ApiPaymentsSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  PrivacyRoute: PrivacyRoute,
  ApiApplicationsRoute: ApiApplicationsRoute,
  PricingSuccessRoute: PricingSuccessRoute,
  ApiAdminAuthRoute: ApiAdminAuthRoute,
  ApiAdminPaymentsRoute: ApiAdminPaymentsRoute,
  ApiPaymentsCheckoutRoute: ApiPaymentsCheckoutRoute,
  ApiPaymentsInvoiceRoute: ApiPaymentsInvoiceRoute,
  ApiPaymentsSessionRoute: ApiPaymentsSessionRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
